# Generated by Django 5.2.17 on 2026-09-14 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nombre y apellido')),
                ('identification', models.CharField(max_length=40, unique=True, verbose_name='Cédula / identificación')),
                ('employee_code', models.CharField(max_length=40, unique=True, verbose_name='Ficha / código de empleado')),
                ('hid_card_code', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Código de tarjeta HID')),
                ('position', models.CharField(max_length=120, verbose_name='Cargo / puesto')),
                ('department', models.CharField(max_length=120, verbose_name='Departamento')),
                ('management', models.CharField(max_length=120, verbose_name='Gerencia')),
                ('emergency_phone', models.CharField(blank=True, max_length=40, verbose_name='Teléfono de contacto de emergencia')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=160, verbose_name='Nombre del contacto de emergencia')),
                ('photo', models.ImageField(upload_to='employees/%Y/%m/', verbose_name='Foto del empleado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ('full_name',),
            },
        ),
    ]
