# Generated by Django 5.2.17 on 2026-09-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_code',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees_employee',
        ),
    ]
