# Generated by Django 5.2.17 on 2026-09-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_employee_code_alter_employee_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hid_card_code',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True, verbose_name='Código legado'),
        ),
    ]
