# Generated by Django 5.2.17 on 2026-09-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_remove_employee_shift_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='employee',
            name='punctuality_tolerance_minutes',
            field=models.PositiveSmallIntegerField(blank=True, default=15, null=True, verbose_name='Tolerancia de puntualidad (minutos)'),
        ),
    ]
