# Generated by Django 5.2.17 on 2026-09-23 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='workday_hours',
            field=models.DecimalField(decimal_places=2, default=9, max_digits=4, verbose_name='Horas de jornada'),
        ),
    ]
