# Generated by Django 5.2.18 on 2026-10-08 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HIDReaderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Garita Principal",
                        max_length=120,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "port",
                    models.CharField(
                        default="COM3",
                        help_text="COM1, COM3 en Windows o /dev/ttyUSB0 en Linux",
                        max_length=80,
                        verbose_name="Puerto",
                    ),
                ),
                (
                    "baud_rate",
                    models.IntegerField(
                        choices=[
                            (1200, "1200"),
                            (2400, "2400"),
                            (4800, "4800"),
                            (9600, "9600"),
                            (19200, "19200"),
                        ],
                        default=9600,
                        verbose_name="Velocidad",
                    ),
                ),
                (
                    "data_bits",
                    models.IntegerField(
                        choices=[(7, "7"), (8, "8")],
                        default=8,
                        verbose_name="Bits de datos",
                    ),
                ),
                (
                    "parity",
                    models.CharField(
                        choices=[
                            ("N", "N / Ninguna"),
                            ("E", "E / Par"),
                            ("O", "O / Impar"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="Paridad",
                    ),
                ),
                (
                    "stop_bits",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2")],
                        default=1,
                        verbose_name="Bits de parada",
                    ),
                ),
                (
                    "timeout",
                    models.FloatField(default=1.0, verbose_name="Tiempo de espera (s)"),
                ),
                (
                    "wiegand_format",
                    models.CharField(
                        default="Wiegand 26-bit",
                        max_length=60,
                        verbose_name="Formato Wiegand",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Lector activo"),
                ),
            ],
            options={
                "verbose_name": "Configuración de lector HID",
                "verbose_name_plural": "Configuración de lectores HID",
                "db_table": "core_hid_reader_config",
            },
        ),
        migrations.CreateModel(
            name="UserSecurity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("failed_login_attempts", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marked_at",
                    models.DateTimeField(verbose_name="Fecha y hora del marcaje"),
                ),
                (
                    "mark_type",
                    models.CharField(
                        choices=[("entry", "Entrada"), ("exit", "Salida")],
                        max_length=10,
                        verbose_name="Tipo de marcaje",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="Registro manual",
                        max_length=120,
                        verbose_name="Origen / dispositivo",
                    ),
                ),
                (
                    "capture_mode",
                    models.CharField(
                        choices=[("hid", "Lector HID"), ("manual", "Registro manual")],
                        default="manual",
                        max_length=10,
                        verbose_name="Modo de captura",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attendance_logs",
                        to="employees.employee",
                    ),
                ),
                (
                    "registered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de marcaje",
                "verbose_name_plural": "Registros de marcaje",
                "db_table": "core_attendance_log",
                "ordering": ("-marked_at",),
                "indexes": [
                    models.Index(fields=["marked_at"], name="attendance_time_idx"),
                    models.Index(
                        fields=["employee", "-marked_at", "-id"],
                        name="attendance_latest_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("unknown_card", "Tarjeta no reconocida"),
                            ("blocked_employee", "Empleado sin acceso"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de evento",
                    ),
                ),
                (
                    "employee_status",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Estatus del empleado"
                    ),
                ),
                (
                    "hid_card_code",
                    models.CharField(
                        blank=True,
                        max_length=80,
                        verbose_name="Código de tarjeta leído",
                    ),
                ),
                (
                    "mark_type",
                    models.CharField(
                        blank=True,
                        choices=[("entry", "Entrada"), ("exit", "Salida")],
                        max_length=10,
                        verbose_name="Tipo solicitado",
                    ),
                ),
                ("reason", models.CharField(max_length=255, verbose_name="Motivo")),
                (
                    "source",
                    models.CharField(
                        max_length=120, verbose_name="Origen / dispositivo"
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y hora"
                    ),
                ),
                (
                    "attempted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de seguridad",
                "verbose_name_plural": "Eventos de seguridad",
                "db_table": "core_security_event",
                "ordering": ("-occurred_at", "-pk"),
                "indexes": [
                    models.Index(fields=["occurred_at"], name="security_event_time_idx")
                ],
            },
        ),
    ]
