# Generated by Django 5.2.18 on 2026-10-08 22:32

from django.db import migrations, models

ROLES = ("Sistemas", "Seguridad", "Recursos Humanos")


def create_role_groups(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    for name in ROLES:
        Group.objects.get_or_create(name=name)


def delete_role_groups(apps, schema_editor):
    apps.get_model("auth", "Group").objects.filter(name__in=ROLES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersecurity",
            name="locked_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Bloqueada hasta"
            ),
        ),
        migrations.RunPython(create_role_groups, delete_role_groups),
    ]
