# Generated by Django 5.2.17 on 2026-09-14 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('employees', '0002_remove_employee_employee_code_alter_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnrecognizedAttendanceAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid_card_code', models.CharField(db_index=True, max_length=80, verbose_name='Código HID leído')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del intento')),
                ('source', models.CharField(default='Web', max_length=120, verbose_name='Origen / dispositivo')),
            ],
            options={
                'verbose_name': 'Intento de marcaje no reconocido',
                'verbose_name_plural': 'Intentos de marcaje no reconocidos',
                'db_table': 'core_unrecognized_attendance_attempt',
                'ordering': ('-attempted_at',),
                'indexes': [models.Index(fields=['attempted_at'], name='attendance_attempt_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid_card_code', models.CharField(db_index=True, max_length=80, verbose_name='Código HID capturado')),
                ('marked_at', models.DateTimeField(verbose_name='Fecha y hora del marcaje')),
                ('mark_type', models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Salida'), ('auto', 'Auto / Sugerido')], default='auto', max_length=10, verbose_name='Tipo de marcaje')),
                ('source', models.CharField(default='Web', max_length=120, verbose_name='Origen / dispositivo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_logs', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Registro de marcaje',
                'verbose_name_plural': 'Registros de marcaje',
                'db_table': 'core_attendance_log',
                'ordering': ('-marked_at',),
                'indexes': [models.Index(fields=['marked_at'], name='attendance_time_idx'), models.Index(fields=['employee'], name='attendance_employee_idx')],
            },
        ),
    ]
