# Generated by Django 5.2.17 on 2026-09-14 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_unrecognizedattendanceattempt_attendancelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='capture_mode',
            field=models.CharField(choices=[('hid', 'Tarjeta HID'), ('manual', 'Registro manual')], default='hid', max_length=10, verbose_name='Modo de captura'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_registrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
