# Generated by Django 5.2.18 on 2026-10-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_roles_and_login_lockout"),
    ]

    operations = [
        migrations.AddField(
            model_name="hidreaderconfig",
            name="last_seen_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Última señal del lector"
            ),
        ),
        migrations.AddField(
            model_name="hidreaderconfig",
            name="status",
            field=models.CharField(
                choices=[
                    ("connected", "Conectado"),
                    ("error", "Con error"),
                    ("stopped", "Detenido"),
                ],
                default="stopped",
                max_length=10,
                verbose_name="Estado del lector",
            ),
        ),
        migrations.AddField(
            model_name="hidreaderconfig",
            name="status_message",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Detalle del estado"
            ),
        ),
    ]
