# Generated by Django 5.2.18 on 2026-10-09 01:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_reader_heartbeat"),
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "backup_enabled",
                    models.BooleanField(
                        default=False, verbose_name="Respaldos automáticos activos"
                    ),
                ),
                (
                    "backup_path",
                    models.CharField(
                        blank=True,
                        help_text="Ruta local o de red, p. ej. \\\\SERVIDOR\\Respaldos\\Marcajix",
                        max_length=400,
                        verbose_name="Carpeta de respaldos",
                    ),
                ),
                (
                    "backup_time",
                    models.TimeField(
                        default=datetime.time(23, 0),
                        verbose_name="Hora del respaldo diario",
                    ),
                ),
                (
                    "backup_retention_days",
                    models.PositiveSmallIntegerField(
                        default=30, verbose_name="Conservar respaldos (días)"
                    ),
                ),
                (
                    "last_backup_attempt_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último intento de respaldo"
                    ),
                ),
                (
                    "last_backup_ok_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último respaldo correcto"
                    ),
                ),
                (
                    "last_backup_status",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        verbose_name="Estado del último respaldo",
                    ),
                ),
                (
                    "last_backup_message",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Detalle del último respaldo",
                    ),
                ),
                (
                    "last_backup_file",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Último archivo de respaldo",
                    ),
                ),
                (
                    "allow_attendance_corrections",
                    models.BooleanField(
                        default=False, verbose_name="Permitir correcciones de marcajes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del sistema",
                "verbose_name_plural": "Configuración del sistema",
                "db_table": "core_system_settings",
            },
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="correction_reason",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Motivo de la corrección"
            ),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="void_reason",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Motivo de la anulación"
            ),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="voided_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Anulado el"
            ),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="voided_attendance_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="attendancelog",
            name="capture_mode",
            field=models.CharField(
                choices=[
                    ("hid", "Lector HID"),
                    ("manual", "Registro manual"),
                    ("correction", "Corrección de RRHH"),
                ],
                default="manual",
                max_length=10,
                verbose_name="Modo de captura",
            ),
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=120)),
                ("kind", models.CharField(max_length=30, verbose_name="Tipo")),
                (
                    "audience",
                    models.CharField(
                        choices=[("door", "Garita"), ("system", "Sistema")],
                        max_length=10,
                        verbose_name="Para",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Información"),
                            ("warning", "Advertencia"),
                            ("critical", "Crítica"),
                        ],
                        default="warning",
                        max_length=10,
                        verbose_name="Gravedad",
                    ),
                ),
                ("title", models.CharField(max_length=160, verbose_name="Título")),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Detalle"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Fecha"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resuelta"
                    ),
                ),
                ("auto_resolved", models.BooleanField(default=False)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="employees.employee",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta",
                "verbose_name_plural": "Alertas",
                "db_table": "core_alert",
                "ordering": ("-created_at", "-pk"),
                "indexes": [
                    models.Index(
                        fields=["resolved_at", "audience"], name="alert_open_idx"
                    )
                ],
            },
        ),
    ]
