# Generated by Django 5.2.17 on 2026-09-15 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendancelog_capture_mode_and_more'),
        ('employees', '0002_remove_employee_employee_code_alter_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hid_card_code', models.CharField(db_index=True, max_length=80, verbose_name='Código HID leído')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('source', models.CharField(default='Web', max_length=120, verbose_name='Origen / dispositivo')),
                ('alert_type', models.CharField(choices=[('inactive_employee', 'Empleado inactivo'), ('unknown_card', 'Tarjeta no reconocida')], max_length=30, verbose_name='Tipo de alerta')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_alerts', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Alerta de seguridad',
                'verbose_name_plural': 'Alertas de seguridad',
                'db_table': 'core_security_alert',
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['occurred_at'], name='security_alert_time_idx'), models.Index(fields=['alert_type'], name='security_alert_type_idx')],
            },
        ),
    ]
