# Generated by Django 5.2.17 on 2026-09-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_securityalert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='capture_mode',
            field=models.CharField(choices=[('manual', 'Registro manual')], default='manual', max_length=10, verbose_name='Modo de captura'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='hid_card_code',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, verbose_name='Código legado'),
        ),
    ]
