# Generated by Django 5.2.17 on 2026-09-23 20:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_attendanceattempt'),
        ('employees', '0011_alter_employee_hire_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='session_status',
            field=models.CharField(choices=[('complete', 'Completa'), ('incomplete', 'Incompleta'), ('orphan', 'Huérfana')], db_index=True, default='complete', max_length=15, verbose_name='Estado de la sesión'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['employee', 'session_status'], name='attendance_session_status_idx'),
        ),
    ]
