# Generated by Django 5.2.17 on 2026-09-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_hidreaderconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='capture_mode',
            field=models.CharField(choices=[('hid', 'Lector HID'), ('manual', 'Registro manual')], default='manual', max_length=10, verbose_name='Modo de captura'),
        ),
    ]
